version: '3'
services:
  database:
    container_name: postgres-datmsc1
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - 'C:\Users\LENOVO\data\postgres\datmsc2:/data/postgres'
    env_file:
      - datmsc2.env